//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicadoDental.EF_PicadoDental_WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ClienteIDField;
        
        private int PersonaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Cita[] CitasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Persona PersonaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ClienteID {
            get {
                return this.ClienteIDField;
            }
            set {
                if ((this.ClienteIDField.Equals(value) != true)) {
                    this.ClienteIDField = value;
                    this.RaisePropertyChanged("ClienteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PersonaID {
            get {
                return this.PersonaIDField;
            }
            set {
                if ((this.PersonaIDField.Equals(value) != true)) {
                    this.PersonaIDField = value;
                    this.RaisePropertyChanged("PersonaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public PicadoDental.EF_PicadoDental_WS.Cita[] Citas {
            get {
                return this.CitasField;
            }
            set {
                if ((object.ReferenceEquals(this.CitasField, value) != true)) {
                    this.CitasField = value;
                    this.RaisePropertyChanged("Citas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public PicadoDental.EF_PicadoDental_WS.Persona Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PersonaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoField;
        
        private int GeneroIDField;
        
        private System.Nullable<int> CredencialIDField;
        
        private int TipoCuentaIDField;
        
        private int ContactoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Cliente[] ClientesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Contacto ContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Credencial CredencialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Genero GeneroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.TipoCuenta TipoCuentaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PersonaID {
            get {
                return this.PersonaIDField;
            }
            set {
                if ((this.PersonaIDField.Equals(value) != true)) {
                    this.PersonaIDField = value;
                    this.RaisePropertyChanged("PersonaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PrimerApellido {
            get {
                return this.PrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoField, value) != true)) {
                    this.PrimerApellidoField = value;
                    this.RaisePropertyChanged("PrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SegundoApellido {
            get {
                return this.SegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoField, value) != true)) {
                    this.SegundoApellidoField = value;
                    this.RaisePropertyChanged("SegundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int GeneroID {
            get {
                return this.GeneroIDField;
            }
            set {
                if ((this.GeneroIDField.Equals(value) != true)) {
                    this.GeneroIDField = value;
                    this.RaisePropertyChanged("GeneroID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> CredencialID {
            get {
                return this.CredencialIDField;
            }
            set {
                if ((this.CredencialIDField.Equals(value) != true)) {
                    this.CredencialIDField = value;
                    this.RaisePropertyChanged("CredencialID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int TipoCuentaID {
            get {
                return this.TipoCuentaIDField;
            }
            set {
                if ((this.TipoCuentaIDField.Equals(value) != true)) {
                    this.TipoCuentaIDField = value;
                    this.RaisePropertyChanged("TipoCuentaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int ContactoID {
            get {
                return this.ContactoIDField;
            }
            set {
                if ((this.ContactoIDField.Equals(value) != true)) {
                    this.ContactoIDField = value;
                    this.RaisePropertyChanged("ContactoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public PicadoDental.EF_PicadoDental_WS.Cliente[] Clientes {
            get {
                return this.ClientesField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientesField, value) != true)) {
                    this.ClientesField = value;
                    this.RaisePropertyChanged("Clientes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public PicadoDental.EF_PicadoDental_WS.Contacto Contacto {
            get {
                return this.ContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactoField, value) != true)) {
                    this.ContactoField = value;
                    this.RaisePropertyChanged("Contacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public PicadoDental.EF_PicadoDental_WS.Credencial Credencial {
            get {
                return this.CredencialField;
            }
            set {
                if ((object.ReferenceEquals(this.CredencialField, value) != true)) {
                    this.CredencialField = value;
                    this.RaisePropertyChanged("Credencial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public PicadoDental.EF_PicadoDental_WS.Genero Genero {
            get {
                return this.GeneroField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneroField, value) != true)) {
                    this.GeneroField = value;
                    this.RaisePropertyChanged("Genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public PicadoDental.EF_PicadoDental_WS.TipoCuenta TipoCuenta {
            get {
                return this.TipoCuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoCuentaField, value) != true)) {
                    this.TipoCuentaField = value;
                    this.RaisePropertyChanged("TipoCuenta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cita", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cita : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CitaIDField;
        
        private int ClienteIDField;
        
        private int PersonaIDField;
        
        private System.DateTime FechaHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescCitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Cliente ClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CitaID {
            get {
                return this.CitaIDField;
            }
            set {
                if ((this.CitaIDField.Equals(value) != true)) {
                    this.CitaIDField = value;
                    this.RaisePropertyChanged("CitaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ClienteID {
            get {
                return this.ClienteIDField;
            }
            set {
                if ((this.ClienteIDField.Equals(value) != true)) {
                    this.ClienteIDField = value;
                    this.RaisePropertyChanged("ClienteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PersonaID {
            get {
                return this.PersonaIDField;
            }
            set {
                if ((this.PersonaIDField.Equals(value) != true)) {
                    this.PersonaIDField = value;
                    this.RaisePropertyChanged("PersonaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime FechaHora {
            get {
                return this.FechaHoraField;
            }
            set {
                if ((this.FechaHoraField.Equals(value) != true)) {
                    this.FechaHoraField = value;
                    this.RaisePropertyChanged("FechaHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DescCita {
            get {
                return this.DescCitaField;
            }
            set {
                if ((object.ReferenceEquals(this.DescCitaField, value) != true)) {
                    this.DescCitaField = value;
                    this.RaisePropertyChanged("DescCita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Comentarios {
            get {
                return this.ComentariosField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentariosField, value) != true)) {
                    this.ComentariosField = value;
                    this.RaisePropertyChanged("Comentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public PicadoDental.EF_PicadoDental_WS.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contacto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Contacto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ContactoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Persona[] PersonasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ContactoID {
            get {
                return this.ContactoIDField;
            }
            set {
                if ((this.ContactoIDField.Equals(value) != true)) {
                    this.ContactoIDField = value;
                    this.RaisePropertyChanged("ContactoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public PicadoDental.EF_PicadoDental_WS.Persona[] Personas {
            get {
                return this.PersonasField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonasField, value) != true)) {
                    this.PersonasField = value;
                    this.RaisePropertyChanged("Personas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credencial", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Credencial : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CredencialIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Persona[] PersonasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CredencialID {
            get {
                return this.CredencialIDField;
            }
            set {
                if ((this.CredencialIDField.Equals(value) != true)) {
                    this.CredencialIDField = value;
                    this.RaisePropertyChanged("CredencialID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public PicadoDental.EF_PicadoDental_WS.Persona[] Personas {
            get {
                return this.PersonasField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonasField, value) != true)) {
                    this.PersonasField = value;
                    this.RaisePropertyChanged("Personas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Genero", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Genero : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int GeneroIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescGeneroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Persona[] PersonasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int GeneroID {
            get {
                return this.GeneroIDField;
            }
            set {
                if ((this.GeneroIDField.Equals(value) != true)) {
                    this.GeneroIDField = value;
                    this.RaisePropertyChanged("GeneroID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DescGenero {
            get {
                return this.DescGeneroField;
            }
            set {
                if ((object.ReferenceEquals(this.DescGeneroField, value) != true)) {
                    this.DescGeneroField = value;
                    this.RaisePropertyChanged("DescGenero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public PicadoDental.EF_PicadoDental_WS.Persona[] Personas {
            get {
                return this.PersonasField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonasField, value) != true)) {
                    this.PersonasField = value;
                    this.RaisePropertyChanged("Personas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoCuenta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TipoCuenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int TipoCuentaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescTipoCuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Persona[] PersonasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TipoCuentaID {
            get {
                return this.TipoCuentaIDField;
            }
            set {
                if ((this.TipoCuentaIDField.Equals(value) != true)) {
                    this.TipoCuentaIDField = value;
                    this.RaisePropertyChanged("TipoCuentaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DescTipoCuenta {
            get {
                return this.DescTipoCuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.DescTipoCuentaField, value) != true)) {
                    this.DescTipoCuentaField = value;
                    this.RaisePropertyChanged("DescTipoCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public PicadoDental.EF_PicadoDental_WS.Persona[] Personas {
            get {
                return this.PersonasField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonasField, value) != true)) {
                    this.PersonasField = value;
                    this.RaisePropertyChanged("Personas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EF_PicadoDental_WS.EF_PicadoDentalSoap")]
    public interface EF_PicadoDentalSoap {
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogIn", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.LogInResponse LogIn(PicadoDental.EF_PicadoDental_WS.LogInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogIn", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.LogInResponse> LogInAsync(PicadoDental.EF_PicadoDental_WS.LogInRequest request);
        
        // CODEGEN: Generating message contract since element name ClientListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientList", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.ClientListResponse ClientList(PicadoDental.EF_PicadoDental_WS.ClientListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientList", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ClientListResponse> ClientListAsync(PicadoDental.EF_PicadoDental_WS.ClientListRequest request);
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewClient", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.NewClientResponse NewClient(PicadoDental.EF_PicadoDental_WS.NewClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewClient", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.NewClientResponse> NewClientAsync(PicadoDental.EF_PicadoDental_WS.NewClientRequest request);
        
        // CODEGEN: Generating message contract since element name telefono from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyClient", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.ModifyClientResponse ModifyClient(PicadoDental.EF_PicadoDental_WS.ModifyClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyClient", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ModifyClientResponse> ModifyClientAsync(PicadoDental.EF_PicadoDental_WS.ModifyClientRequest request);
        
        // CODEGEN: Generating message contract since element name fechaHora from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewAppointment", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.NewAppointmentResponse NewAppointment(PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewAppointment", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.NewAppointmentResponse> NewAppointmentAsync(PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest request);
        
        // CODEGEN: Generating message contract since element name doctorId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyAppointment", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponse ModifyAppointment(PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyAppointment", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponse> ModifyAppointmentAsync(PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogIn", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.LogInRequestBody Body;
        
        public LogInRequest() {
        }
        
        public LogInRequest(PicadoDental.EF_PicadoDental_WS.LogInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        public LogInRequestBody() {
        }
        
        public LogInRequestBody(string usuario, string contrasena) {
            this.usuario = usuario;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.LogInResponseBody Body;
        
        public LogInResponse() {
        }
        
        public LogInResponse(PicadoDental.EF_PicadoDental_WS.LogInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ArrayOfString LogInResult;
        
        public LogInResponseBody() {
        }
        
        public LogInResponseBody(PicadoDental.EF_PicadoDental_WS.ArrayOfString LogInResult) {
            this.LogInResult = LogInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClientListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClientList", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ClientListRequestBody Body;
        
        public ClientListRequest() {
        }
        
        public ClientListRequest(PicadoDental.EF_PicadoDental_WS.ClientListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ClientListRequestBody {
        
        public ClientListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClientListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClientListResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ClientListResponseBody Body;
        
        public ClientListResponse() {
        }
        
        public ClientListResponse(PicadoDental.EF_PicadoDental_WS.ClientListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PicadoDental.EF_PicadoDental_WS.Cliente[] ClientListResult;
        
        public ClientListResponseBody() {
        }
        
        public ClientListResponseBody(PicadoDental.EF_PicadoDental_WS.Cliente[] ClientListResult) {
            this.ClientListResult = ClientListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewClient", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.NewClientRequestBody Body;
        
        public NewClientRequest() {
        }
        
        public NewClientRequest(PicadoDental.EF_PicadoDental_WS.NewClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string primerApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string segundoApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int generoID;
        
        public NewClientRequestBody() {
        }
        
        public NewClientRequestBody(string nombre, string primerApellido, string segundoApellido, string telefono, string correo, int generoID) {
            this.nombre = nombre;
            this.primerApellido = primerApellido;
            this.segundoApellido = segundoApellido;
            this.telefono = telefono;
            this.correo = correo;
            this.generoID = generoID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewClientResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.NewClientResponseBody Body;
        
        public NewClientResponse() {
        }
        
        public NewClientResponse(PicadoDental.EF_PicadoDental_WS.NewClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class NewClientResponseBody {
        
        public NewClientResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyClient", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ModifyClientRequestBody Body;
        
        public ModifyClientRequest() {
        }
        
        public ModifyClientRequest(PicadoDental.EF_PicadoDental_WS.ModifyClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModifyClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int personaId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string correo;
        
        public ModifyClientRequestBody() {
        }
        
        public ModifyClientRequestBody(int personaId, string telefono, string correo) {
            this.personaId = personaId;
            this.telefono = telefono;
            this.correo = correo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyClientResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ModifyClientResponseBody Body;
        
        public ModifyClientResponse() {
        }
        
        public ModifyClientResponse(PicadoDental.EF_PicadoDental_WS.ModifyClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModifyClientResponseBody {
        
        public ModifyClientResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewAppointmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewAppointment", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.NewAppointmentRequestBody Body;
        
        public NewAppointmentRequest() {
        }
        
        public NewAppointmentRequest(PicadoDental.EF_PicadoDental_WS.NewAppointmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewAppointmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int clienteId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int doctorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fechaHora;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string comentarios;
        
        public NewAppointmentRequestBody() {
        }
        
        public NewAppointmentRequestBody(int clienteId, int doctorId, string fechaHora, string descripcion, string comentarios) {
            this.clienteId = clienteId;
            this.doctorId = doctorId;
            this.fechaHora = fechaHora;
            this.descripcion = descripcion;
            this.comentarios = comentarios;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewAppointmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewAppointmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.NewAppointmentResponseBody Body;
        
        public NewAppointmentResponse() {
        }
        
        public NewAppointmentResponse(PicadoDental.EF_PicadoDental_WS.NewAppointmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class NewAppointmentResponseBody {
        
        public NewAppointmentResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyAppointmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyAppointment", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequestBody Body;
        
        public ModifyAppointmentRequest() {
        }
        
        public ModifyAppointmentRequest(PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModifyAppointmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int citaId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string doctorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fechaHora;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string comentarios;
        
        public ModifyAppointmentRequestBody() {
        }
        
        public ModifyAppointmentRequestBody(int citaId, string doctorId, string fechaHora, string descripcion, string comentarios) {
            this.citaId = citaId;
            this.doctorId = doctorId;
            this.fechaHora = fechaHora;
            this.descripcion = descripcion;
            this.comentarios = comentarios;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyAppointmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyAppointmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponseBody Body;
        
        public ModifyAppointmentResponse() {
        }
        
        public ModifyAppointmentResponse(PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModifyAppointmentResponseBody {
        
        public ModifyAppointmentResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EF_PicadoDentalSoapChannel : PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EF_PicadoDentalSoapClient : System.ServiceModel.ClientBase<PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap>, PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap {
        
        public EF_PicadoDentalSoapClient() {
        }
        
        public EF_PicadoDentalSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EF_PicadoDentalSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EF_PicadoDentalSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EF_PicadoDentalSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.LogInResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.LogIn(PicadoDental.EF_PicadoDental_WS.LogInRequest request) {
            return base.Channel.LogIn(request);
        }
        
        public PicadoDental.EF_PicadoDental_WS.ArrayOfString LogIn(string usuario, string contrasena) {
            PicadoDental.EF_PicadoDental_WS.LogInRequest inValue = new PicadoDental.EF_PicadoDental_WS.LogInRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.LogInRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            PicadoDental.EF_PicadoDental_WS.LogInResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).LogIn(inValue);
            return retVal.Body.LogInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.LogInResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.LogInAsync(PicadoDental.EF_PicadoDental_WS.LogInRequest request) {
            return base.Channel.LogInAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.LogInResponse> LogInAsync(string usuario, string contrasena) {
            PicadoDental.EF_PicadoDental_WS.LogInRequest inValue = new PicadoDental.EF_PicadoDental_WS.LogInRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.LogInRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).LogInAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.ClientListResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ClientList(PicadoDental.EF_PicadoDental_WS.ClientListRequest request) {
            return base.Channel.ClientList(request);
        }
        
        public PicadoDental.EF_PicadoDental_WS.Cliente[] ClientList() {
            PicadoDental.EF_PicadoDental_WS.ClientListRequest inValue = new PicadoDental.EF_PicadoDental_WS.ClientListRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ClientListRequestBody();
            PicadoDental.EF_PicadoDental_WS.ClientListResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ClientList(inValue);
            return retVal.Body.ClientListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ClientListResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ClientListAsync(PicadoDental.EF_PicadoDental_WS.ClientListRequest request) {
            return base.Channel.ClientListAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ClientListResponse> ClientListAsync() {
            PicadoDental.EF_PicadoDental_WS.ClientListRequest inValue = new PicadoDental.EF_PicadoDental_WS.ClientListRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ClientListRequestBody();
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ClientListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.NewClientResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.NewClient(PicadoDental.EF_PicadoDental_WS.NewClientRequest request) {
            return base.Channel.NewClient(request);
        }
        
        public void NewClient(string nombre, string primerApellido, string segundoApellido, string telefono, string correo, int generoID) {
            PicadoDental.EF_PicadoDental_WS.NewClientRequest inValue = new PicadoDental.EF_PicadoDental_WS.NewClientRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.NewClientRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.primerApellido = primerApellido;
            inValue.Body.segundoApellido = segundoApellido;
            inValue.Body.telefono = telefono;
            inValue.Body.correo = correo;
            inValue.Body.generoID = generoID;
            PicadoDental.EF_PicadoDental_WS.NewClientResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).NewClient(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.NewClientResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.NewClientAsync(PicadoDental.EF_PicadoDental_WS.NewClientRequest request) {
            return base.Channel.NewClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.NewClientResponse> NewClientAsync(string nombre, string primerApellido, string segundoApellido, string telefono, string correo, int generoID) {
            PicadoDental.EF_PicadoDental_WS.NewClientRequest inValue = new PicadoDental.EF_PicadoDental_WS.NewClientRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.NewClientRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.primerApellido = primerApellido;
            inValue.Body.segundoApellido = segundoApellido;
            inValue.Body.telefono = telefono;
            inValue.Body.correo = correo;
            inValue.Body.generoID = generoID;
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).NewClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.ModifyClientResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ModifyClient(PicadoDental.EF_PicadoDental_WS.ModifyClientRequest request) {
            return base.Channel.ModifyClient(request);
        }
        
        public void ModifyClient(int personaId, string telefono, string correo) {
            PicadoDental.EF_PicadoDental_WS.ModifyClientRequest inValue = new PicadoDental.EF_PicadoDental_WS.ModifyClientRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ModifyClientRequestBody();
            inValue.Body.personaId = personaId;
            inValue.Body.telefono = telefono;
            inValue.Body.correo = correo;
            PicadoDental.EF_PicadoDental_WS.ModifyClientResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ModifyClient(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ModifyClientResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ModifyClientAsync(PicadoDental.EF_PicadoDental_WS.ModifyClientRequest request) {
            return base.Channel.ModifyClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ModifyClientResponse> ModifyClientAsync(int personaId, string telefono, string correo) {
            PicadoDental.EF_PicadoDental_WS.ModifyClientRequest inValue = new PicadoDental.EF_PicadoDental_WS.ModifyClientRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ModifyClientRequestBody();
            inValue.Body.personaId = personaId;
            inValue.Body.telefono = telefono;
            inValue.Body.correo = correo;
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ModifyClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.NewAppointmentResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.NewAppointment(PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest request) {
            return base.Channel.NewAppointment(request);
        }
        
        public void NewAppointment(int clienteId, int doctorId, string fechaHora, string descripcion, string comentarios) {
            PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest inValue = new PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.NewAppointmentRequestBody();
            inValue.Body.clienteId = clienteId;
            inValue.Body.doctorId = doctorId;
            inValue.Body.fechaHora = fechaHora;
            inValue.Body.descripcion = descripcion;
            inValue.Body.comentarios = comentarios;
            PicadoDental.EF_PicadoDental_WS.NewAppointmentResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).NewAppointment(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.NewAppointmentResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.NewAppointmentAsync(PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest request) {
            return base.Channel.NewAppointmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.NewAppointmentResponse> NewAppointmentAsync(int clienteId, int doctorId, string fechaHora, string descripcion, string comentarios) {
            PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest inValue = new PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.NewAppointmentRequestBody();
            inValue.Body.clienteId = clienteId;
            inValue.Body.doctorId = doctorId;
            inValue.Body.fechaHora = fechaHora;
            inValue.Body.descripcion = descripcion;
            inValue.Body.comentarios = comentarios;
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).NewAppointmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ModifyAppointment(PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest request) {
            return base.Channel.ModifyAppointment(request);
        }
        
        public void ModifyAppointment(int citaId, string doctorId, string fechaHora, string descripcion, string comentarios) {
            PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest inValue = new PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequestBody();
            inValue.Body.citaId = citaId;
            inValue.Body.doctorId = doctorId;
            inValue.Body.fechaHora = fechaHora;
            inValue.Body.descripcion = descripcion;
            inValue.Body.comentarios = comentarios;
            PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ModifyAppointment(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ModifyAppointmentAsync(PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest request) {
            return base.Channel.ModifyAppointmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponse> ModifyAppointmentAsync(int citaId, string doctorId, string fechaHora, string descripcion, string comentarios) {
            PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest inValue = new PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequestBody();
            inValue.Body.citaId = citaId;
            inValue.Body.doctorId = doctorId;
            inValue.Body.fechaHora = fechaHora;
            inValue.Body.descripcion = descripcion;
            inValue.Body.comentarios = comentarios;
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ModifyAppointmentAsync(inValue);
        }
    }
}
