//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicadoDental.EF_PicadoDental_WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientePOCO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ClientePOCO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ClienteIDField;
        
        private int PersonaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ClienteID {
            get {
                return this.ClienteIDField;
            }
            set {
                if ((this.ClienteIDField.Equals(value) != true)) {
                    this.ClienteIDField = value;
                    this.RaisePropertyChanged("ClienteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PersonaID {
            get {
                return this.PersonaIDField;
            }
            set {
                if ((this.PersonaIDField.Equals(value) != true)) {
                    this.PersonaIDField = value;
                    this.RaisePropertyChanged("PersonaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CitaPOCO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CitaPOCO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DoctorNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DoctorApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetallesField;
        
        private int ClienteIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DoctorTelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DoctorCorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteTelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteCorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentariosField;
        
        private int CitaIDField;
        
        private int DoctorIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClienteNombre {
            get {
                return this.ClienteNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteNombreField, value) != true)) {
                    this.ClienteNombreField = value;
                    this.RaisePropertyChanged("ClienteNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ClienteApellidos {
            get {
                return this.ClienteApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteApellidosField, value) != true)) {
                    this.ClienteApellidosField = value;
                    this.RaisePropertyChanged("ClienteApellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DoctorNombre {
            get {
                return this.DoctorNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.DoctorNombreField, value) != true)) {
                    this.DoctorNombreField = value;
                    this.RaisePropertyChanged("DoctorNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DoctorApellidos {
            get {
                return this.DoctorApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.DoctorApellidosField, value) != true)) {
                    this.DoctorApellidosField = value;
                    this.RaisePropertyChanged("DoctorApellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Detalles {
            get {
                return this.DetallesField;
            }
            set {
                if ((object.ReferenceEquals(this.DetallesField, value) != true)) {
                    this.DetallesField = value;
                    this.RaisePropertyChanged("Detalles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int ClienteID {
            get {
                return this.ClienteIDField;
            }
            set {
                if ((this.ClienteIDField.Equals(value) != true)) {
                    this.ClienteIDField = value;
                    this.RaisePropertyChanged("ClienteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string DoctorTelefono {
            get {
                return this.DoctorTelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.DoctorTelefonoField, value) != true)) {
                    this.DoctorTelefonoField = value;
                    this.RaisePropertyChanged("DoctorTelefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string DoctorCorreo {
            get {
                return this.DoctorCorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.DoctorCorreoField, value) != true)) {
                    this.DoctorCorreoField = value;
                    this.RaisePropertyChanged("DoctorCorreo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ClienteTelefono {
            get {
                return this.ClienteTelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteTelefonoField, value) != true)) {
                    this.ClienteTelefonoField = value;
                    this.RaisePropertyChanged("ClienteTelefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ClienteCorreo {
            get {
                return this.ClienteCorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteCorreoField, value) != true)) {
                    this.ClienteCorreoField = value;
                    this.RaisePropertyChanged("ClienteCorreo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Comentarios {
            get {
                return this.ComentariosField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentariosField, value) != true)) {
                    this.ComentariosField = value;
                    this.RaisePropertyChanged("Comentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int CitaID {
            get {
                return this.CitaIDField;
            }
            set {
                if ((this.CitaIDField.Equals(value) != true)) {
                    this.CitaIDField = value;
                    this.RaisePropertyChanged("CitaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int DoctorID {
            get {
                return this.DoctorIDField;
            }
            set {
                if ((this.DoctorIDField.Equals(value) != true)) {
                    this.DoctorIDField = value;
                    this.RaisePropertyChanged("DoctorID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EF_PicadoDental_WS.EF_PicadoDentalSoap")]
    public interface EF_PicadoDentalSoap {
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogIn", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.LogInResponse LogIn(PicadoDental.EF_PicadoDental_WS.LogInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogIn", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.LogInResponse> LogInAsync(PicadoDental.EF_PicadoDental_WS.LogInRequest request);
        
        // CODEGEN: Generating message contract since element name ClientListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientList", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.ClientListResponse ClientList(PicadoDental.EF_PicadoDental_WS.ClientListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientList", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ClientListResponse> ClientListAsync(PicadoDental.EF_PicadoDental_WS.ClientListRequest request);
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewPerson", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.NewPersonResponse NewPerson(PicadoDental.EF_PicadoDental_WS.NewPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.NewPersonResponse> NewPersonAsync(PicadoDental.EF_PicadoDental_WS.NewPersonRequest request);
        
        // CODEGEN: Generating message contract since element name telefono from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyClient", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.ModifyClientResponse ModifyClient(PicadoDental.EF_PicadoDental_WS.ModifyClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyClient", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ModifyClientResponse> ModifyClientAsync(PicadoDental.EF_PicadoDental_WS.ModifyClientRequest request);
        
        // CODEGEN: Generating message contract since element name CitaListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CitaList", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.CitaListResponse CitaList(PicadoDental.EF_PicadoDental_WS.CitaListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CitaList", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.CitaListResponse> CitaListAsync(PicadoDental.EF_PicadoDental_WS.CitaListRequest request);
        
        // CODEGEN: Generating message contract since element name CitaListByIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CitaListByID", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.CitaListByIDResponse CitaListByID(PicadoDental.EF_PicadoDental_WS.CitaListByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CitaListByID", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.CitaListByIDResponse> CitaListByIDAsync(PicadoDental.EF_PicadoDental_WS.CitaListByIDRequest request);
        
        // CODEGEN: Generating message contract since element name ListaDoctoresResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaDoctores", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.ListaDoctoresResponse ListaDoctores(PicadoDental.EF_PicadoDental_WS.ListaDoctoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaDoctores", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ListaDoctoresResponse> ListaDoctoresAsync(PicadoDental.EF_PicadoDental_WS.ListaDoctoresRequest request);
        
        // CODEGEN: Generating message contract since element name ListaClientesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaClientes", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.ListaClientesResponse ListaClientes(PicadoDental.EF_PicadoDental_WS.ListaClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ListaClientesResponse> ListaClientesAsync(PicadoDental.EF_PicadoDental_WS.ListaClientesRequest request);
        
        // CODEGEN: Generating message contract since element name fechaHora from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewAppointment", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.NewAppointmentResponse NewAppointment(PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewAppointment", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.NewAppointmentResponse> NewAppointmentAsync(PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest request);
        
        // CODEGEN: Generating message contract since element name doctorId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyAppointment", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponse ModifyAppointment(PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyAppointment", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponse> ModifyAppointmentAsync(PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogIn", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.LogInRequestBody Body;
        
        public LogInRequest() {
        }
        
        public LogInRequest(PicadoDental.EF_PicadoDental_WS.LogInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        public LogInRequestBody() {
        }
        
        public LogInRequestBody(string usuario, string contrasena) {
            this.usuario = usuario;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.LogInResponseBody Body;
        
        public LogInResponse() {
        }
        
        public LogInResponse(PicadoDental.EF_PicadoDental_WS.LogInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ArrayOfString LogInResult;
        
        public LogInResponseBody() {
        }
        
        public LogInResponseBody(PicadoDental.EF_PicadoDental_WS.ArrayOfString LogInResult) {
            this.LogInResult = LogInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClientListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClientList", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ClientListRequestBody Body;
        
        public ClientListRequest() {
        }
        
        public ClientListRequest(PicadoDental.EF_PicadoDental_WS.ClientListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ClientListRequestBody {
        
        public ClientListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClientListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClientListResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ClientListResponseBody Body;
        
        public ClientListResponse() {
        }
        
        public ClientListResponse(PicadoDental.EF_PicadoDental_WS.ClientListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ClientePOCO[] ClientListResult;
        
        public ClientListResponseBody() {
        }
        
        public ClientListResponseBody(PicadoDental.EF_PicadoDental_WS.ClientePOCO[] ClientListResult) {
            this.ClientListResult = ClientListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewPerson", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.NewPersonRequestBody Body;
        
        public NewPersonRequest() {
        }
        
        public NewPersonRequest(PicadoDental.EF_PicadoDental_WS.NewPersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewPersonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string primerApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string segundoApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int generoID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int cedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int tipoCuentaID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string contrasena;
        
        public NewPersonRequestBody() {
        }
        
        public NewPersonRequestBody(string nombre, string primerApellido, string segundoApellido, string telefono, string correo, int generoID, int cedula, int tipoCuentaID, string usuario, string contrasena) {
            this.nombre = nombre;
            this.primerApellido = primerApellido;
            this.segundoApellido = segundoApellido;
            this.telefono = telefono;
            this.correo = correo;
            this.generoID = generoID;
            this.cedula = cedula;
            this.tipoCuentaID = tipoCuentaID;
            this.usuario = usuario;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewPersonResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.NewPersonResponseBody Body;
        
        public NewPersonResponse() {
        }
        
        public NewPersonResponse(PicadoDental.EF_PicadoDental_WS.NewPersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class NewPersonResponseBody {
        
        public NewPersonResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyClient", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ModifyClientRequestBody Body;
        
        public ModifyClientRequest() {
        }
        
        public ModifyClientRequest(PicadoDental.EF_PicadoDental_WS.ModifyClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModifyClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int personaId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string correo;
        
        public ModifyClientRequestBody() {
        }
        
        public ModifyClientRequestBody(int personaId, string telefono, string correo) {
            this.personaId = personaId;
            this.telefono = telefono;
            this.correo = correo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyClientResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ModifyClientResponseBody Body;
        
        public ModifyClientResponse() {
        }
        
        public ModifyClientResponse(PicadoDental.EF_PicadoDental_WS.ModifyClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModifyClientResponseBody {
        
        public ModifyClientResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CitaListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CitaList", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.CitaListRequestBody Body;
        
        public CitaListRequest() {
        }
        
        public CitaListRequest(PicadoDental.EF_PicadoDental_WS.CitaListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CitaListRequestBody {
        
        public CitaListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CitaListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CitaListResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.CitaListResponseBody Body;
        
        public CitaListResponse() {
        }
        
        public CitaListResponse(PicadoDental.EF_PicadoDental_WS.CitaListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CitaListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PicadoDental.EF_PicadoDental_WS.CitaPOCO[] CitaListResult;
        
        public CitaListResponseBody() {
        }
        
        public CitaListResponseBody(PicadoDental.EF_PicadoDental_WS.CitaPOCO[] CitaListResult) {
            this.CitaListResult = CitaListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CitaListByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CitaListByID", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.CitaListByIDRequestBody Body;
        
        public CitaListByIDRequest() {
        }
        
        public CitaListByIDRequest(PicadoDental.EF_PicadoDental_WS.CitaListByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CitaListByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public CitaListByIDRequestBody() {
        }
        
        public CitaListByIDRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CitaListByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CitaListByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.CitaListByIDResponseBody Body;
        
        public CitaListByIDResponse() {
        }
        
        public CitaListByIDResponse(PicadoDental.EF_PicadoDental_WS.CitaListByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CitaListByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PicadoDental.EF_PicadoDental_WS.CitaPOCO[] CitaListByIDResult;
        
        public CitaListByIDResponseBody() {
        }
        
        public CitaListByIDResponseBody(PicadoDental.EF_PicadoDental_WS.CitaPOCO[] CitaListByIDResult) {
            this.CitaListByIDResult = CitaListByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaDoctoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaDoctores", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ListaDoctoresRequestBody Body;
        
        public ListaDoctoresRequest() {
        }
        
        public ListaDoctoresRequest(PicadoDental.EF_PicadoDental_WS.ListaDoctoresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaDoctoresRequestBody {
        
        public ListaDoctoresRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaDoctoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaDoctoresResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ListaDoctoresResponseBody Body;
        
        public ListaDoctoresResponse() {
        }
        
        public ListaDoctoresResponse(PicadoDental.EF_PicadoDental_WS.ListaDoctoresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaDoctoresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PicadoDental.EF_PicadoDental_WS.CitaPOCO[] ListaDoctoresResult;
        
        public ListaDoctoresResponseBody() {
        }
        
        public ListaDoctoresResponseBody(PicadoDental.EF_PicadoDental_WS.CitaPOCO[] ListaDoctoresResult) {
            this.ListaDoctoresResult = ListaDoctoresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaClientes", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ListaClientesRequestBody Body;
        
        public ListaClientesRequest() {
        }
        
        public ListaClientesRequest(PicadoDental.EF_PicadoDental_WS.ListaClientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaClientesRequestBody {
        
        public ListaClientesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaClientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ListaClientesResponseBody Body;
        
        public ListaClientesResponse() {
        }
        
        public ListaClientesResponse(PicadoDental.EF_PicadoDental_WS.ListaClientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaClientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PicadoDental.EF_PicadoDental_WS.CitaPOCO[] ListaClientesResult;
        
        public ListaClientesResponseBody() {
        }
        
        public ListaClientesResponseBody(PicadoDental.EF_PicadoDental_WS.CitaPOCO[] ListaClientesResult) {
            this.ListaClientesResult = ListaClientesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewAppointmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewAppointment", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.NewAppointmentRequestBody Body;
        
        public NewAppointmentRequest() {
        }
        
        public NewAppointmentRequest(PicadoDental.EF_PicadoDental_WS.NewAppointmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewAppointmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int clienteId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int doctorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fechaHora;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string comentarios;
        
        public NewAppointmentRequestBody() {
        }
        
        public NewAppointmentRequestBody(int clienteId, int doctorId, string fechaHora, string descripcion, string comentarios) {
            this.clienteId = clienteId;
            this.doctorId = doctorId;
            this.fechaHora = fechaHora;
            this.descripcion = descripcion;
            this.comentarios = comentarios;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewAppointmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewAppointmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.NewAppointmentResponseBody Body;
        
        public NewAppointmentResponse() {
        }
        
        public NewAppointmentResponse(PicadoDental.EF_PicadoDental_WS.NewAppointmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class NewAppointmentResponseBody {
        
        public NewAppointmentResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyAppointmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyAppointment", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequestBody Body;
        
        public ModifyAppointmentRequest() {
        }
        
        public ModifyAppointmentRequest(PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModifyAppointmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int citaId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string doctorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fechaHora;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string comentarios;
        
        public ModifyAppointmentRequestBody() {
        }
        
        public ModifyAppointmentRequestBody(int citaId, string doctorId, string fechaHora, string descripcion, string comentarios) {
            this.citaId = citaId;
            this.doctorId = doctorId;
            this.fechaHora = fechaHora;
            this.descripcion = descripcion;
            this.comentarios = comentarios;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyAppointmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyAppointmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponseBody Body;
        
        public ModifyAppointmentResponse() {
        }
        
        public ModifyAppointmentResponse(PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModifyAppointmentResponseBody {
        
        public ModifyAppointmentResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EF_PicadoDentalSoapChannel : PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EF_PicadoDentalSoapClient : System.ServiceModel.ClientBase<PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap>, PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap {
        
        public EF_PicadoDentalSoapClient() {
        }
        
        public EF_PicadoDentalSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EF_PicadoDentalSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EF_PicadoDentalSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EF_PicadoDentalSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.LogInResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.LogIn(PicadoDental.EF_PicadoDental_WS.LogInRequest request) {
            return base.Channel.LogIn(request);
        }
        
        public PicadoDental.EF_PicadoDental_WS.ArrayOfString LogIn(string usuario, string contrasena) {
            PicadoDental.EF_PicadoDental_WS.LogInRequest inValue = new PicadoDental.EF_PicadoDental_WS.LogInRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.LogInRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            PicadoDental.EF_PicadoDental_WS.LogInResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).LogIn(inValue);
            return retVal.Body.LogInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.LogInResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.LogInAsync(PicadoDental.EF_PicadoDental_WS.LogInRequest request) {
            return base.Channel.LogInAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.LogInResponse> LogInAsync(string usuario, string contrasena) {
            PicadoDental.EF_PicadoDental_WS.LogInRequest inValue = new PicadoDental.EF_PicadoDental_WS.LogInRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.LogInRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).LogInAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.ClientListResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ClientList(PicadoDental.EF_PicadoDental_WS.ClientListRequest request) {
            return base.Channel.ClientList(request);
        }
        
        public PicadoDental.EF_PicadoDental_WS.ClientePOCO[] ClientList() {
            PicadoDental.EF_PicadoDental_WS.ClientListRequest inValue = new PicadoDental.EF_PicadoDental_WS.ClientListRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ClientListRequestBody();
            PicadoDental.EF_PicadoDental_WS.ClientListResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ClientList(inValue);
            return retVal.Body.ClientListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ClientListResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ClientListAsync(PicadoDental.EF_PicadoDental_WS.ClientListRequest request) {
            return base.Channel.ClientListAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ClientListResponse> ClientListAsync() {
            PicadoDental.EF_PicadoDental_WS.ClientListRequest inValue = new PicadoDental.EF_PicadoDental_WS.ClientListRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ClientListRequestBody();
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ClientListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.NewPersonResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.NewPerson(PicadoDental.EF_PicadoDental_WS.NewPersonRequest request) {
            return base.Channel.NewPerson(request);
        }
        
        public void NewPerson(string nombre, string primerApellido, string segundoApellido, string telefono, string correo, int generoID, int cedula, int tipoCuentaID, string usuario, string contrasena) {
            PicadoDental.EF_PicadoDental_WS.NewPersonRequest inValue = new PicadoDental.EF_PicadoDental_WS.NewPersonRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.NewPersonRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.primerApellido = primerApellido;
            inValue.Body.segundoApellido = segundoApellido;
            inValue.Body.telefono = telefono;
            inValue.Body.correo = correo;
            inValue.Body.generoID = generoID;
            inValue.Body.cedula = cedula;
            inValue.Body.tipoCuentaID = tipoCuentaID;
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            PicadoDental.EF_PicadoDental_WS.NewPersonResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).NewPerson(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.NewPersonResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.NewPersonAsync(PicadoDental.EF_PicadoDental_WS.NewPersonRequest request) {
            return base.Channel.NewPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.NewPersonResponse> NewPersonAsync(string nombre, string primerApellido, string segundoApellido, string telefono, string correo, int generoID, int cedula, int tipoCuentaID, string usuario, string contrasena) {
            PicadoDental.EF_PicadoDental_WS.NewPersonRequest inValue = new PicadoDental.EF_PicadoDental_WS.NewPersonRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.NewPersonRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.primerApellido = primerApellido;
            inValue.Body.segundoApellido = segundoApellido;
            inValue.Body.telefono = telefono;
            inValue.Body.correo = correo;
            inValue.Body.generoID = generoID;
            inValue.Body.cedula = cedula;
            inValue.Body.tipoCuentaID = tipoCuentaID;
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).NewPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.ModifyClientResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ModifyClient(PicadoDental.EF_PicadoDental_WS.ModifyClientRequest request) {
            return base.Channel.ModifyClient(request);
        }
        
        public void ModifyClient(int personaId, string telefono, string correo) {
            PicadoDental.EF_PicadoDental_WS.ModifyClientRequest inValue = new PicadoDental.EF_PicadoDental_WS.ModifyClientRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ModifyClientRequestBody();
            inValue.Body.personaId = personaId;
            inValue.Body.telefono = telefono;
            inValue.Body.correo = correo;
            PicadoDental.EF_PicadoDental_WS.ModifyClientResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ModifyClient(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ModifyClientResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ModifyClientAsync(PicadoDental.EF_PicadoDental_WS.ModifyClientRequest request) {
            return base.Channel.ModifyClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ModifyClientResponse> ModifyClientAsync(int personaId, string telefono, string correo) {
            PicadoDental.EF_PicadoDental_WS.ModifyClientRequest inValue = new PicadoDental.EF_PicadoDental_WS.ModifyClientRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ModifyClientRequestBody();
            inValue.Body.personaId = personaId;
            inValue.Body.telefono = telefono;
            inValue.Body.correo = correo;
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ModifyClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.CitaListResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.CitaList(PicadoDental.EF_PicadoDental_WS.CitaListRequest request) {
            return base.Channel.CitaList(request);
        }
        
        public PicadoDental.EF_PicadoDental_WS.CitaPOCO[] CitaList() {
            PicadoDental.EF_PicadoDental_WS.CitaListRequest inValue = new PicadoDental.EF_PicadoDental_WS.CitaListRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.CitaListRequestBody();
            PicadoDental.EF_PicadoDental_WS.CitaListResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).CitaList(inValue);
            return retVal.Body.CitaListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.CitaListResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.CitaListAsync(PicadoDental.EF_PicadoDental_WS.CitaListRequest request) {
            return base.Channel.CitaListAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.CitaListResponse> CitaListAsync() {
            PicadoDental.EF_PicadoDental_WS.CitaListRequest inValue = new PicadoDental.EF_PicadoDental_WS.CitaListRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.CitaListRequestBody();
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).CitaListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.CitaListByIDResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.CitaListByID(PicadoDental.EF_PicadoDental_WS.CitaListByIDRequest request) {
            return base.Channel.CitaListByID(request);
        }
        
        public PicadoDental.EF_PicadoDental_WS.CitaPOCO[] CitaListByID(int id) {
            PicadoDental.EF_PicadoDental_WS.CitaListByIDRequest inValue = new PicadoDental.EF_PicadoDental_WS.CitaListByIDRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.CitaListByIDRequestBody();
            inValue.Body.id = id;
            PicadoDental.EF_PicadoDental_WS.CitaListByIDResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).CitaListByID(inValue);
            return retVal.Body.CitaListByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.CitaListByIDResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.CitaListByIDAsync(PicadoDental.EF_PicadoDental_WS.CitaListByIDRequest request) {
            return base.Channel.CitaListByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.CitaListByIDResponse> CitaListByIDAsync(int id) {
            PicadoDental.EF_PicadoDental_WS.CitaListByIDRequest inValue = new PicadoDental.EF_PicadoDental_WS.CitaListByIDRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.CitaListByIDRequestBody();
            inValue.Body.id = id;
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).CitaListByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.ListaDoctoresResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ListaDoctores(PicadoDental.EF_PicadoDental_WS.ListaDoctoresRequest request) {
            return base.Channel.ListaDoctores(request);
        }
        
        public PicadoDental.EF_PicadoDental_WS.CitaPOCO[] ListaDoctores() {
            PicadoDental.EF_PicadoDental_WS.ListaDoctoresRequest inValue = new PicadoDental.EF_PicadoDental_WS.ListaDoctoresRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ListaDoctoresRequestBody();
            PicadoDental.EF_PicadoDental_WS.ListaDoctoresResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ListaDoctores(inValue);
            return retVal.Body.ListaDoctoresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ListaDoctoresResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ListaDoctoresAsync(PicadoDental.EF_PicadoDental_WS.ListaDoctoresRequest request) {
            return base.Channel.ListaDoctoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ListaDoctoresResponse> ListaDoctoresAsync() {
            PicadoDental.EF_PicadoDental_WS.ListaDoctoresRequest inValue = new PicadoDental.EF_PicadoDental_WS.ListaDoctoresRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ListaDoctoresRequestBody();
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ListaDoctoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.ListaClientesResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ListaClientes(PicadoDental.EF_PicadoDental_WS.ListaClientesRequest request) {
            return base.Channel.ListaClientes(request);
        }
        
        public PicadoDental.EF_PicadoDental_WS.CitaPOCO[] ListaClientes() {
            PicadoDental.EF_PicadoDental_WS.ListaClientesRequest inValue = new PicadoDental.EF_PicadoDental_WS.ListaClientesRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ListaClientesRequestBody();
            PicadoDental.EF_PicadoDental_WS.ListaClientesResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ListaClientes(inValue);
            return retVal.Body.ListaClientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ListaClientesResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ListaClientesAsync(PicadoDental.EF_PicadoDental_WS.ListaClientesRequest request) {
            return base.Channel.ListaClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ListaClientesResponse> ListaClientesAsync() {
            PicadoDental.EF_PicadoDental_WS.ListaClientesRequest inValue = new PicadoDental.EF_PicadoDental_WS.ListaClientesRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ListaClientesRequestBody();
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ListaClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.NewAppointmentResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.NewAppointment(PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest request) {
            return base.Channel.NewAppointment(request);
        }
        
        public void NewAppointment(int clienteId, int doctorId, string fechaHora, string descripcion, string comentarios) {
            PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest inValue = new PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.NewAppointmentRequestBody();
            inValue.Body.clienteId = clienteId;
            inValue.Body.doctorId = doctorId;
            inValue.Body.fechaHora = fechaHora;
            inValue.Body.descripcion = descripcion;
            inValue.Body.comentarios = comentarios;
            PicadoDental.EF_PicadoDental_WS.NewAppointmentResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).NewAppointment(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.NewAppointmentResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.NewAppointmentAsync(PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest request) {
            return base.Channel.NewAppointmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.NewAppointmentResponse> NewAppointmentAsync(int clienteId, int doctorId, string fechaHora, string descripcion, string comentarios) {
            PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest inValue = new PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.NewAppointmentRequestBody();
            inValue.Body.clienteId = clienteId;
            inValue.Body.doctorId = doctorId;
            inValue.Body.fechaHora = fechaHora;
            inValue.Body.descripcion = descripcion;
            inValue.Body.comentarios = comentarios;
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).NewAppointmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ModifyAppointment(PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest request) {
            return base.Channel.ModifyAppointment(request);
        }
        
        public void ModifyAppointment(int citaId, string doctorId, string fechaHora, string descripcion, string comentarios) {
            PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest inValue = new PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequestBody();
            inValue.Body.citaId = citaId;
            inValue.Body.doctorId = doctorId;
            inValue.Body.fechaHora = fechaHora;
            inValue.Body.descripcion = descripcion;
            inValue.Body.comentarios = comentarios;
            PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ModifyAppointment(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ModifyAppointmentAsync(PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest request) {
            return base.Channel.ModifyAppointmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponse> ModifyAppointmentAsync(int citaId, string doctorId, string fechaHora, string descripcion, string comentarios) {
            PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest inValue = new PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequestBody();
            inValue.Body.citaId = citaId;
            inValue.Body.doctorId = doctorId;
            inValue.Body.fechaHora = fechaHora;
            inValue.Body.descripcion = descripcion;
            inValue.Body.comentarios = comentarios;
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ModifyAppointmentAsync(inValue);
        }
    }
}
