//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicadoDental.EF_PicadoDental_WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short ClienteIdField;
        
        private short PersonaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Cita[] CitasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Persona PersonaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short PersonaId {
            get {
                return this.PersonaIdField;
            }
            set {
                if ((this.PersonaIdField.Equals(value) != true)) {
                    this.PersonaIdField = value;
                    this.RaisePropertyChanged("PersonaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public PicadoDental.EF_PicadoDental_WS.Cita[] Citas {
            get {
                return this.CitasField;
            }
            set {
                if ((object.ReferenceEquals(this.CitasField, value) != true)) {
                    this.CitasField = value;
                    this.RaisePropertyChanged("Citas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public PicadoDental.EF_PicadoDental_WS.Persona Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short PersonaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        private System.Nullable<short> GeneroIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Admin[] AdminsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Cliente[] ClientesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Doctor[] DoctorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Genero GeneroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short PersonaId {
            get {
                return this.PersonaIdField;
            }
            set {
                if ((this.PersonaIdField.Equals(value) != true)) {
                    this.PersonaIdField = value;
                    this.RaisePropertyChanged("PersonaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PrimerApellido {
            get {
                return this.PrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoField, value) != true)) {
                    this.PrimerApellidoField = value;
                    this.RaisePropertyChanged("PrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SegundoApellido {
            get {
                return this.SegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoField, value) != true)) {
                    this.SegundoApellidoField = value;
                    this.RaisePropertyChanged("SegundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<short> GeneroId {
            get {
                return this.GeneroIdField;
            }
            set {
                if ((this.GeneroIdField.Equals(value) != true)) {
                    this.GeneroIdField = value;
                    this.RaisePropertyChanged("GeneroId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public PicadoDental.EF_PicadoDental_WS.Admin[] Admins {
            get {
                return this.AdminsField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminsField, value) != true)) {
                    this.AdminsField = value;
                    this.RaisePropertyChanged("Admins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public PicadoDental.EF_PicadoDental_WS.Cliente[] Clientes {
            get {
                return this.ClientesField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientesField, value) != true)) {
                    this.ClientesField = value;
                    this.RaisePropertyChanged("Clientes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public PicadoDental.EF_PicadoDental_WS.Doctor[] Doctors {
            get {
                return this.DoctorsField;
            }
            set {
                if ((object.ReferenceEquals(this.DoctorsField, value) != true)) {
                    this.DoctorsField = value;
                    this.RaisePropertyChanged("Doctors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public PicadoDental.EF_PicadoDental_WS.Genero Genero {
            get {
                return this.GeneroField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneroField, value) != true)) {
                    this.GeneroField = value;
                    this.RaisePropertyChanged("Genero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cita", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cita : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short CitaIdField;
        
        private short ClienteIdField;
        
        private short DoctorIdField;
        
        private System.Nullable<System.DateTime> FechaHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Doctor DoctorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short CitaId {
            get {
                return this.CitaIdField;
            }
            set {
                if ((this.CitaIdField.Equals(value) != true)) {
                    this.CitaIdField = value;
                    this.RaisePropertyChanged("CitaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short ClienteId {
            get {
                return this.ClienteIdField;
            }
            set {
                if ((this.ClienteIdField.Equals(value) != true)) {
                    this.ClienteIdField = value;
                    this.RaisePropertyChanged("ClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short DoctorId {
            get {
                return this.DoctorIdField;
            }
            set {
                if ((this.DoctorIdField.Equals(value) != true)) {
                    this.DoctorIdField = value;
                    this.RaisePropertyChanged("DoctorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> FechaHora {
            get {
                return this.FechaHoraField;
            }
            set {
                if ((this.FechaHoraField.Equals(value) != true)) {
                    this.FechaHoraField = value;
                    this.RaisePropertyChanged("FechaHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Comentarios {
            get {
                return this.ComentariosField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentariosField, value) != true)) {
                    this.ComentariosField = value;
                    this.RaisePropertyChanged("Comentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public PicadoDental.EF_PicadoDental_WS.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public PicadoDental.EF_PicadoDental_WS.Doctor Doctor {
            get {
                return this.DoctorField;
            }
            set {
                if ((object.ReferenceEquals(this.DoctorField, value) != true)) {
                    this.DoctorField = value;
                    this.RaisePropertyChanged("Doctor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Doctor", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Doctor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short DoctorIdField;
        
        private short PersonaIdField;
        
        private short UsuarioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EspecialidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Cita[] CitasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Persona PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Usuario UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short DoctorId {
            get {
                return this.DoctorIdField;
            }
            set {
                if ((this.DoctorIdField.Equals(value) != true)) {
                    this.DoctorIdField = value;
                    this.RaisePropertyChanged("DoctorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short PersonaId {
            get {
                return this.PersonaIdField;
            }
            set {
                if ((this.PersonaIdField.Equals(value) != true)) {
                    this.PersonaIdField = value;
                    this.RaisePropertyChanged("PersonaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((this.UsuarioIdField.Equals(value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Especialidad {
            get {
                return this.EspecialidadField;
            }
            set {
                if ((object.ReferenceEquals(this.EspecialidadField, value) != true)) {
                    this.EspecialidadField = value;
                    this.RaisePropertyChanged("Especialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public PicadoDental.EF_PicadoDental_WS.Cita[] Citas {
            get {
                return this.CitasField;
            }
            set {
                if ((object.ReferenceEquals(this.CitasField, value) != true)) {
                    this.CitasField = value;
                    this.RaisePropertyChanged("Citas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public PicadoDental.EF_PicadoDental_WS.Persona Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public PicadoDental.EF_PicadoDental_WS.Usuario Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short UsuarioIdField;
        
        private System.Nullable<short> PersonaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usuario1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Admin[] AdminsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Doctor[] DoctorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((this.UsuarioIdField.Equals(value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<short> PersonaId {
            get {
                return this.PersonaIdField;
            }
            set {
                if ((this.PersonaIdField.Equals(value) != true)) {
                    this.PersonaIdField = value;
                    this.RaisePropertyChanged("PersonaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Usuario1 {
            get {
                return this.Usuario1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Usuario1Field, value) != true)) {
                    this.Usuario1Field = value;
                    this.RaisePropertyChanged("Usuario1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public PicadoDental.EF_PicadoDental_WS.Admin[] Admins {
            get {
                return this.AdminsField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminsField, value) != true)) {
                    this.AdminsField = value;
                    this.RaisePropertyChanged("Admins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public PicadoDental.EF_PicadoDental_WS.Doctor[] Doctors {
            get {
                return this.DoctorsField;
            }
            set {
                if ((object.ReferenceEquals(this.DoctorsField, value) != true)) {
                    this.DoctorsField = value;
                    this.RaisePropertyChanged("Doctors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Genero", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Genero : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short GeneroIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescipcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Persona[] PersonasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short GeneroId {
            get {
                return this.GeneroIdField;
            }
            set {
                if ((this.GeneroIdField.Equals(value) != true)) {
                    this.GeneroIdField = value;
                    this.RaisePropertyChanged("GeneroId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Descipcion {
            get {
                return this.DescipcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescipcionField, value) != true)) {
                    this.DescipcionField = value;
                    this.RaisePropertyChanged("Descipcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public PicadoDental.EF_PicadoDental_WS.Persona[] Personas {
            get {
                return this.PersonasField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonasField, value) != true)) {
                    this.PersonasField = value;
                    this.RaisePropertyChanged("Personas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Admin", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Admin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short AdminIdField;
        
        private short PersonaIdField;
        
        private short UsuarioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Persona PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental_WS.Usuario UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short AdminId {
            get {
                return this.AdminIdField;
            }
            set {
                if ((this.AdminIdField.Equals(value) != true)) {
                    this.AdminIdField = value;
                    this.RaisePropertyChanged("AdminId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short PersonaId {
            get {
                return this.PersonaIdField;
            }
            set {
                if ((this.PersonaIdField.Equals(value) != true)) {
                    this.PersonaIdField = value;
                    this.RaisePropertyChanged("PersonaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((this.UsuarioIdField.Equals(value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public PicadoDental.EF_PicadoDental_WS.Persona Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public PicadoDental.EF_PicadoDental_WS.Usuario Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EF_PicadoDental_WS.EF_PicadoDentalSoap")]
    public interface EF_PicadoDentalSoap {
        
        // CODEGEN: Generating message contract since element name usuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogIn", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.LogInResponse LogIn(PicadoDental.EF_PicadoDental_WS.LogInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogIn", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.LogInResponse> LogInAsync(PicadoDental.EF_PicadoDental_WS.LogInRequest request);
        
        // CODEGEN: Generating message contract since element name ClientListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientList", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.ClientListResponse ClientList(PicadoDental.EF_PicadoDental_WS.ClientListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientList", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ClientListResponse> ClientListAsync(PicadoDental.EF_PicadoDental_WS.ClientListRequest request);
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewClient", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.NewClientResponse NewClient(PicadoDental.EF_PicadoDental_WS.NewClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewClient", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.NewClientResponse> NewClientAsync(PicadoDental.EF_PicadoDental_WS.NewClientRequest request);
        
        // CODEGEN: Generating message contract since element name telefono from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyClient", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.ModifyClientResponse ModifyClient(PicadoDental.EF_PicadoDental_WS.ModifyClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyClient", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ModifyClientResponse> ModifyClientAsync(PicadoDental.EF_PicadoDental_WS.ModifyClientRequest request);
        
        // CODEGEN: Generating message contract since element name descripcion from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewAppointment", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.NewAppointmentResponse NewAppointment(PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewAppointment", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.NewAppointmentResponse> NewAppointmentAsync(PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest request);
        
        // CODEGEN: Generating message contract since element name descripcion from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyAppointment", ReplyAction="*")]
        PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponse ModifyAppointment(PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyAppointment", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponse> ModifyAppointmentAsync(PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogIn", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.LogInRequestBody Body;
        
        public LogInRequest() {
        }
        
        public LogInRequest(PicadoDental.EF_PicadoDental_WS.LogInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        public LogInRequestBody() {
        }
        
        public LogInRequestBody(string usuario, string contrasena) {
            this.usuario = usuario;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.LogInResponseBody Body;
        
        public LogInResponse() {
        }
        
        public LogInResponse(PicadoDental.EF_PicadoDental_WS.LogInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LogInResult;
        
        public LogInResponseBody() {
        }
        
        public LogInResponseBody(bool LogInResult) {
            this.LogInResult = LogInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClientListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClientList", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ClientListRequestBody Body;
        
        public ClientListRequest() {
        }
        
        public ClientListRequest(PicadoDental.EF_PicadoDental_WS.ClientListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ClientListRequestBody {
        
        public ClientListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClientListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClientListResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ClientListResponseBody Body;
        
        public ClientListResponse() {
        }
        
        public ClientListResponse(PicadoDental.EF_PicadoDental_WS.ClientListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PicadoDental.EF_PicadoDental_WS.Cliente[] ClientListResult;
        
        public ClientListResponseBody() {
        }
        
        public ClientListResponseBody(PicadoDental.EF_PicadoDental_WS.Cliente[] ClientListResult) {
            this.ClientListResult = ClientListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewClient", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.NewClientRequestBody Body;
        
        public NewClientRequest() {
        }
        
        public NewClientRequest(PicadoDental.EF_PicadoDental_WS.NewClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string primerApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string segundoApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public byte generoID;
        
        public NewClientRequestBody() {
        }
        
        public NewClientRequestBody(string nombre, string primerApellido, string segundoApellido, string telefono, string correo, byte generoID) {
            this.nombre = nombre;
            this.primerApellido = primerApellido;
            this.segundoApellido = segundoApellido;
            this.telefono = telefono;
            this.correo = correo;
            this.generoID = generoID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewClientResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.NewClientResponseBody Body;
        
        public NewClientResponse() {
        }
        
        public NewClientResponse(PicadoDental.EF_PicadoDental_WS.NewClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class NewClientResponseBody {
        
        public NewClientResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyClient", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ModifyClientRequestBody Body;
        
        public ModifyClientRequest() {
        }
        
        public ModifyClientRequest(PicadoDental.EF_PicadoDental_WS.ModifyClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModifyClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public short personaId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public byte generoID;
        
        public ModifyClientRequestBody() {
        }
        
        public ModifyClientRequestBody(short personaId, string telefono, string correo, byte generoID) {
            this.personaId = personaId;
            this.telefono = telefono;
            this.correo = correo;
            this.generoID = generoID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyClientResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ModifyClientResponseBody Body;
        
        public ModifyClientResponse() {
        }
        
        public ModifyClientResponse(PicadoDental.EF_PicadoDental_WS.ModifyClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModifyClientResponseBody {
        
        public ModifyClientResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewAppointmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewAppointment", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.NewAppointmentRequestBody Body;
        
        public NewAppointmentRequest() {
        }
        
        public NewAppointmentRequest(PicadoDental.EF_PicadoDental_WS.NewAppointmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewAppointmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public short clienteId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public short doctorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime fechaHora;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string comentarios;
        
        public NewAppointmentRequestBody() {
        }
        
        public NewAppointmentRequestBody(short clienteId, short doctorId, System.DateTime fechaHora, string descripcion, string comentarios) {
            this.clienteId = clienteId;
            this.doctorId = doctorId;
            this.fechaHora = fechaHora;
            this.descripcion = descripcion;
            this.comentarios = comentarios;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewAppointmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewAppointmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.NewAppointmentResponseBody Body;
        
        public NewAppointmentResponse() {
        }
        
        public NewAppointmentResponse(PicadoDental.EF_PicadoDental_WS.NewAppointmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class NewAppointmentResponseBody {
        
        public NewAppointmentResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyAppointmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyAppointment", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequestBody Body;
        
        public ModifyAppointmentRequest() {
        }
        
        public ModifyAppointmentRequest(PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModifyAppointmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public short citaId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public short doctorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime fechaHora;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string comentarios;
        
        public ModifyAppointmentRequestBody() {
        }
        
        public ModifyAppointmentRequestBody(short citaId, short doctorId, System.DateTime fechaHora, string descripcion, string comentarios) {
            this.citaId = citaId;
            this.doctorId = doctorId;
            this.fechaHora = fechaHora;
            this.descripcion = descripcion;
            this.comentarios = comentarios;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyAppointmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyAppointmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponseBody Body;
        
        public ModifyAppointmentResponse() {
        }
        
        public ModifyAppointmentResponse(PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModifyAppointmentResponseBody {
        
        public ModifyAppointmentResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EF_PicadoDentalSoapChannel : PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EF_PicadoDentalSoapClient : System.ServiceModel.ClientBase<PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap>, PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap {
        
        public EF_PicadoDentalSoapClient() {
        }
        
        public EF_PicadoDentalSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EF_PicadoDentalSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EF_PicadoDentalSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EF_PicadoDentalSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.LogInResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.LogIn(PicadoDental.EF_PicadoDental_WS.LogInRequest request) {
            return base.Channel.LogIn(request);
        }
        
        public bool LogIn(string usuario, string contrasena) {
            PicadoDental.EF_PicadoDental_WS.LogInRequest inValue = new PicadoDental.EF_PicadoDental_WS.LogInRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.LogInRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            PicadoDental.EF_PicadoDental_WS.LogInResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).LogIn(inValue);
            return retVal.Body.LogInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.LogInResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.LogInAsync(PicadoDental.EF_PicadoDental_WS.LogInRequest request) {
            return base.Channel.LogInAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.LogInResponse> LogInAsync(string usuario, string contrasena) {
            PicadoDental.EF_PicadoDental_WS.LogInRequest inValue = new PicadoDental.EF_PicadoDental_WS.LogInRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.LogInRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).LogInAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.ClientListResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ClientList(PicadoDental.EF_PicadoDental_WS.ClientListRequest request) {
            return base.Channel.ClientList(request);
        }
        
        public PicadoDental.EF_PicadoDental_WS.Cliente[] ClientList() {
            PicadoDental.EF_PicadoDental_WS.ClientListRequest inValue = new PicadoDental.EF_PicadoDental_WS.ClientListRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ClientListRequestBody();
            PicadoDental.EF_PicadoDental_WS.ClientListResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ClientList(inValue);
            return retVal.Body.ClientListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ClientListResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ClientListAsync(PicadoDental.EF_PicadoDental_WS.ClientListRequest request) {
            return base.Channel.ClientListAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ClientListResponse> ClientListAsync() {
            PicadoDental.EF_PicadoDental_WS.ClientListRequest inValue = new PicadoDental.EF_PicadoDental_WS.ClientListRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ClientListRequestBody();
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ClientListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.NewClientResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.NewClient(PicadoDental.EF_PicadoDental_WS.NewClientRequest request) {
            return base.Channel.NewClient(request);
        }
        
        public void NewClient(string nombre, string primerApellido, string segundoApellido, string telefono, string correo, byte generoID) {
            PicadoDental.EF_PicadoDental_WS.NewClientRequest inValue = new PicadoDental.EF_PicadoDental_WS.NewClientRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.NewClientRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.primerApellido = primerApellido;
            inValue.Body.segundoApellido = segundoApellido;
            inValue.Body.telefono = telefono;
            inValue.Body.correo = correo;
            inValue.Body.generoID = generoID;
            PicadoDental.EF_PicadoDental_WS.NewClientResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).NewClient(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.NewClientResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.NewClientAsync(PicadoDental.EF_PicadoDental_WS.NewClientRequest request) {
            return base.Channel.NewClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.NewClientResponse> NewClientAsync(string nombre, string primerApellido, string segundoApellido, string telefono, string correo, byte generoID) {
            PicadoDental.EF_PicadoDental_WS.NewClientRequest inValue = new PicadoDental.EF_PicadoDental_WS.NewClientRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.NewClientRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.primerApellido = primerApellido;
            inValue.Body.segundoApellido = segundoApellido;
            inValue.Body.telefono = telefono;
            inValue.Body.correo = correo;
            inValue.Body.generoID = generoID;
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).NewClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.ModifyClientResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ModifyClient(PicadoDental.EF_PicadoDental_WS.ModifyClientRequest request) {
            return base.Channel.ModifyClient(request);
        }
        
        public void ModifyClient(short personaId, string telefono, string correo, byte generoID) {
            PicadoDental.EF_PicadoDental_WS.ModifyClientRequest inValue = new PicadoDental.EF_PicadoDental_WS.ModifyClientRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ModifyClientRequestBody();
            inValue.Body.personaId = personaId;
            inValue.Body.telefono = telefono;
            inValue.Body.correo = correo;
            inValue.Body.generoID = generoID;
            PicadoDental.EF_PicadoDental_WS.ModifyClientResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ModifyClient(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ModifyClientResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ModifyClientAsync(PicadoDental.EF_PicadoDental_WS.ModifyClientRequest request) {
            return base.Channel.ModifyClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ModifyClientResponse> ModifyClientAsync(short personaId, string telefono, string correo, byte generoID) {
            PicadoDental.EF_PicadoDental_WS.ModifyClientRequest inValue = new PicadoDental.EF_PicadoDental_WS.ModifyClientRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ModifyClientRequestBody();
            inValue.Body.personaId = personaId;
            inValue.Body.telefono = telefono;
            inValue.Body.correo = correo;
            inValue.Body.generoID = generoID;
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ModifyClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.NewAppointmentResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.NewAppointment(PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest request) {
            return base.Channel.NewAppointment(request);
        }
        
        public void NewAppointment(short clienteId, short doctorId, System.DateTime fechaHora, string descripcion, string comentarios) {
            PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest inValue = new PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.NewAppointmentRequestBody();
            inValue.Body.clienteId = clienteId;
            inValue.Body.doctorId = doctorId;
            inValue.Body.fechaHora = fechaHora;
            inValue.Body.descripcion = descripcion;
            inValue.Body.comentarios = comentarios;
            PicadoDental.EF_PicadoDental_WS.NewAppointmentResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).NewAppointment(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.NewAppointmentResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.NewAppointmentAsync(PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest request) {
            return base.Channel.NewAppointmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.NewAppointmentResponse> NewAppointmentAsync(short clienteId, short doctorId, System.DateTime fechaHora, string descripcion, string comentarios) {
            PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest inValue = new PicadoDental.EF_PicadoDental_WS.NewAppointmentRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.NewAppointmentRequestBody();
            inValue.Body.clienteId = clienteId;
            inValue.Body.doctorId = doctorId;
            inValue.Body.fechaHora = fechaHora;
            inValue.Body.descripcion = descripcion;
            inValue.Body.comentarios = comentarios;
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).NewAppointmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponse PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ModifyAppointment(PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest request) {
            return base.Channel.ModifyAppointment(request);
        }
        
        public void ModifyAppointment(short citaId, short doctorId, System.DateTime fechaHora, string descripcion, string comentarios) {
            PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest inValue = new PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequestBody();
            inValue.Body.citaId = citaId;
            inValue.Body.doctorId = doctorId;
            inValue.Body.fechaHora = fechaHora;
            inValue.Body.descripcion = descripcion;
            inValue.Body.comentarios = comentarios;
            PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponse retVal = ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ModifyAppointment(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponse> PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap.ModifyAppointmentAsync(PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest request) {
            return base.Channel.ModifyAppointmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental_WS.ModifyAppointmentResponse> ModifyAppointmentAsync(short citaId, short doctorId, System.DateTime fechaHora, string descripcion, string comentarios) {
            PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest inValue = new PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental_WS.ModifyAppointmentRequestBody();
            inValue.Body.citaId = citaId;
            inValue.Body.doctorId = doctorId;
            inValue.Body.fechaHora = fechaHora;
            inValue.Body.descripcion = descripcion;
            inValue.Body.comentarios = comentarios;
            return ((PicadoDental.EF_PicadoDental_WS.EF_PicadoDentalSoap)(this)).ModifyAppointmentAsync(inValue);
        }
    }
}
