//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicadoDental.EF_PicadoDental {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short ClienteIDField;
        
        private short PersonaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental.Cita[] CitasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental.Persona PersonaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short ClienteID {
            get {
                return this.ClienteIDField;
            }
            set {
                if ((this.ClienteIDField.Equals(value) != true)) {
                    this.ClienteIDField = value;
                    this.RaisePropertyChanged("ClienteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short PersonaID {
            get {
                return this.PersonaIDField;
            }
            set {
                if ((this.PersonaIDField.Equals(value) != true)) {
                    this.PersonaIDField = value;
                    this.RaisePropertyChanged("PersonaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public PicadoDental.EF_PicadoDental.Cita[] Citas {
            get {
                return this.CitasField;
            }
            set {
                if ((object.ReferenceEquals(this.CitasField, value) != true)) {
                    this.CitasField = value;
                    this.RaisePropertyChanged("Citas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public PicadoDental.EF_PicadoDental.Persona Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short PersonaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        private byte GeneroIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental.Admin[] AdminsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental.Cliente[] ClientesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental.Genero GeneroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short PersonaID {
            get {
                return this.PersonaIDField;
            }
            set {
                if ((this.PersonaIDField.Equals(value) != true)) {
                    this.PersonaIDField = value;
                    this.RaisePropertyChanged("PersonaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PrimerApellido {
            get {
                return this.PrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoField, value) != true)) {
                    this.PrimerApellidoField = value;
                    this.RaisePropertyChanged("PrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SegundoApellido {
            get {
                return this.SegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoField, value) != true)) {
                    this.SegundoApellidoField = value;
                    this.RaisePropertyChanged("SegundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public byte GeneroID {
            get {
                return this.GeneroIDField;
            }
            set {
                if ((this.GeneroIDField.Equals(value) != true)) {
                    this.GeneroIDField = value;
                    this.RaisePropertyChanged("GeneroID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public PicadoDental.EF_PicadoDental.Admin[] Admins {
            get {
                return this.AdminsField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminsField, value) != true)) {
                    this.AdminsField = value;
                    this.RaisePropertyChanged("Admins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public PicadoDental.EF_PicadoDental.Cliente[] Clientes {
            get {
                return this.ClientesField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientesField, value) != true)) {
                    this.ClientesField = value;
                    this.RaisePropertyChanged("Clientes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public PicadoDental.EF_PicadoDental.Genero Genero {
            get {
                return this.GeneroField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneroField, value) != true)) {
                    this.GeneroField = value;
                    this.RaisePropertyChanged("Genero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cita", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cita : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short CitaIDField;
        
        private short ClienteIDField;
        
        private short AdminIDField;
        
        private System.DateTime FechaField;
        
        private System.DateTime HoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental.Admin AdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental.Cliente ClienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short CitaID {
            get {
                return this.CitaIDField;
            }
            set {
                if ((this.CitaIDField.Equals(value) != true)) {
                    this.CitaIDField = value;
                    this.RaisePropertyChanged("CitaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short ClienteID {
            get {
                return this.ClienteIDField;
            }
            set {
                if ((this.ClienteIDField.Equals(value) != true)) {
                    this.ClienteIDField = value;
                    this.RaisePropertyChanged("ClienteID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public short AdminID {
            get {
                return this.AdminIDField;
            }
            set {
                if ((this.AdminIDField.Equals(value) != true)) {
                    this.AdminIDField = value;
                    this.RaisePropertyChanged("AdminID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime Hora {
            get {
                return this.HoraField;
            }
            set {
                if ((this.HoraField.Equals(value) != true)) {
                    this.HoraField = value;
                    this.RaisePropertyChanged("Hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Comentarios {
            get {
                return this.ComentariosField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentariosField, value) != true)) {
                    this.ComentariosField = value;
                    this.RaisePropertyChanged("Comentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public PicadoDental.EF_PicadoDental.Admin Admin {
            get {
                return this.AdminField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminField, value) != true)) {
                    this.AdminField = value;
                    this.RaisePropertyChanged("Admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public PicadoDental.EF_PicadoDental.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Admin", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Admin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short AdminIDField;
        
        private short PersonaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental.Persona PersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental.Cita[] CitasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short AdminID {
            get {
                return this.AdminIDField;
            }
            set {
                if ((this.AdminIDField.Equals(value) != true)) {
                    this.AdminIDField = value;
                    this.RaisePropertyChanged("AdminID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short PersonaID {
            get {
                return this.PersonaIDField;
            }
            set {
                if ((this.PersonaIDField.Equals(value) != true)) {
                    this.PersonaIDField = value;
                    this.RaisePropertyChanged("PersonaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.contrasenaField, value) != true)) {
                    this.contrasenaField = value;
                    this.RaisePropertyChanged("contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public PicadoDental.EF_PicadoDental.Persona Persona {
            get {
                return this.PersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaField, value) != true)) {
                    this.PersonaField = value;
                    this.RaisePropertyChanged("Persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public PicadoDental.EF_PicadoDental.Cita[] Citas {
            get {
                return this.CitasField;
            }
            set {
                if ((object.ReferenceEquals(this.CitasField, value) != true)) {
                    this.CitasField = value;
                    this.RaisePropertyChanged("Citas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Genero", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Genero : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte GeneroIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescGeneroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PicadoDental.EF_PicadoDental.Persona[] PersonasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte GeneroID {
            get {
                return this.GeneroIDField;
            }
            set {
                if ((this.GeneroIDField.Equals(value) != true)) {
                    this.GeneroIDField = value;
                    this.RaisePropertyChanged("GeneroID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DescGenero {
            get {
                return this.DescGeneroField;
            }
            set {
                if ((object.ReferenceEquals(this.DescGeneroField, value) != true)) {
                    this.DescGeneroField = value;
                    this.RaisePropertyChanged("DescGenero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public PicadoDental.EF_PicadoDental.Persona[] Personas {
            get {
                return this.PersonasField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonasField, value) != true)) {
                    this.PersonasField = value;
                    this.RaisePropertyChanged("Personas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EF_PicadoDental.EF_PicadoDentalSoap")]
    public interface EF_PicadoDentalSoap {
        
        // CODEGEN: Generating message contract since element name ClientListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientList", ReplyAction="*")]
        PicadoDental.EF_PicadoDental.ClientListResponse ClientList(PicadoDental.EF_PicadoDental.ClientListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientList", ReplyAction="*")]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental.ClientListResponse> ClientListAsync(PicadoDental.EF_PicadoDental.ClientListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClientListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClientList", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental.ClientListRequestBody Body;
        
        public ClientListRequest() {
        }
        
        public ClientListRequest(PicadoDental.EF_PicadoDental.ClientListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ClientListRequestBody {
        
        public ClientListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClientListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClientListResponse", Namespace="http://tempuri.org/", Order=0)]
        public PicadoDental.EF_PicadoDental.ClientListResponseBody Body;
        
        public ClientListResponse() {
        }
        
        public ClientListResponse(PicadoDental.EF_PicadoDental.ClientListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PicadoDental.EF_PicadoDental.Cliente[] ClientListResult;
        
        public ClientListResponseBody() {
        }
        
        public ClientListResponseBody(PicadoDental.EF_PicadoDental.Cliente[] ClientListResult) {
            this.ClientListResult = ClientListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EF_PicadoDentalSoapChannel : PicadoDental.EF_PicadoDental.EF_PicadoDentalSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EF_PicadoDentalSoapClient : System.ServiceModel.ClientBase<PicadoDental.EF_PicadoDental.EF_PicadoDentalSoap>, PicadoDental.EF_PicadoDental.EF_PicadoDentalSoap {
        
        public EF_PicadoDentalSoapClient() {
        }
        
        public EF_PicadoDentalSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EF_PicadoDentalSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EF_PicadoDentalSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EF_PicadoDentalSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PicadoDental.EF_PicadoDental.ClientListResponse PicadoDental.EF_PicadoDental.EF_PicadoDentalSoap.ClientList(PicadoDental.EF_PicadoDental.ClientListRequest request) {
            return base.Channel.ClientList(request);
        }
        
        public PicadoDental.EF_PicadoDental.Cliente[] ClientList() {
            PicadoDental.EF_PicadoDental.ClientListRequest inValue = new PicadoDental.EF_PicadoDental.ClientListRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental.ClientListRequestBody();
            PicadoDental.EF_PicadoDental.ClientListResponse retVal = ((PicadoDental.EF_PicadoDental.EF_PicadoDentalSoap)(this)).ClientList(inValue);
            return retVal.Body.ClientListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental.ClientListResponse> PicadoDental.EF_PicadoDental.EF_PicadoDentalSoap.ClientListAsync(PicadoDental.EF_PicadoDental.ClientListRequest request) {
            return base.Channel.ClientListAsync(request);
        }
        
        public System.Threading.Tasks.Task<PicadoDental.EF_PicadoDental.ClientListResponse> ClientListAsync() {
            PicadoDental.EF_PicadoDental.ClientListRequest inValue = new PicadoDental.EF_PicadoDental.ClientListRequest();
            inValue.Body = new PicadoDental.EF_PicadoDental.ClientListRequestBody();
            return ((PicadoDental.EF_PicadoDental.EF_PicadoDentalSoap)(this)).ClientListAsync(inValue);
        }
    }
}
